

const Departments = () => {
  return (
    <>
    <div className='p-md-5 p-3'>
        <h1 className='fw-bold text-center mainHead' style={{ letterSpacing: '1px', color: '#3473d8ff' }}>Departments</h1>
         <p className='text-center text-secondary opacity-75  contents'>Specialized medical services across multiple disciplines</p>

         <h2 className='fw-bold text-center mt-md-5  subHead' style={{ letterSpacing: '1px', color: '#3473d8ff' }}>Cardiology</h2>
         <p className='text-secondary opacity-75  contents' style={{textAlign:'justify'}}>The Cardiology Department offers advanced diagnostic and interventional care for heart-related conditions. Led by Dr. Arvind Menon (Senior Cardiologist, MBBS, MD, DM Cardiology) and Dr. Sneha Raj (Interventional Cardiologist, MBBS, MD), the team handles complex cardiac cases with precision. The department provides angiograms, angioplasty, pacemaker implantation, cardiac stress tests, and comprehensive echo evaluations. Patients receive services such as cardiac rehabilitation, hypertension clinics, lipid management, and 24×7 emergency care. Facilities include a fully equipped cath lab, dedicated cardiac ICU, advanced ECG/Holter monitoring, and a modern observation suite designed for quick stabilization and continuous monitoring.</p>

         <h2 className='fw-bold text-center mt-md-5 subHead' style={{ letterSpacing: '1px', color: '#3473d8ff' }}>Pediatrics</h2>
         <p className='text-secondary opacity-75 contents' style={{textAlign:'justify'}}>The Pediatrics Department ensures specialized healthcare for infants, children, and adolescents. Under the expertise of Dr. Nisha Pillai (MBBS, MD Pediatrics) and Dr. Farhan George (Neonatologist, MBBS, DNB), the unit handles routine care, developmental assessments, and complex neonatal conditions. Key procedures include newborn screening, pediatric nebulization, growth monitoring, and nutritional evaluations. The department provides immunization services, pediatric emergency care, developmental therapy, and newborn follow-ups. With a child-friendly NICU, advanced infant monitoring systems, warmers, incubators, and specially designed consultation rooms, the department maintains a safe and comfortable environment for young patients and their families.</p>

         <h2 className='fw-bold text-center mt-md-5 subHead' style={{ letterSpacing: '1px', color: '#3473d8ff' }}>Orthopedics</h2>
         <p className='text-secondary opacity-75 contents' style={{textAlign:'justify'}}>The Orthopedics Department focuses on the treatment of bone, joint, spine, and sports-related injuries. Led by Dr. Vimal Krishna (Orthopedic Surgeon, MBBS, MS Ortho) and Dr. Aanya Roy (Joint Replacement Specialist, MBBS, DNB Ortho), the team manages trauma cases, fractures, joint disorders, and degenerative conditions. Procedures include knee and hip replacement, arthroscopy, spine stabilization surgeries, fracture fixation, and ligament repair. The department offers physiotherapy, pain management sessions, geriatric bone care, post-operative rehabilitation, and sports injury recovery programs. Facilities feature a digital X-ray unit, gait analysis equipment, a rehabilitation gym, and an advanced orthopedic operation theatre.</p>

         <h2 className='fw-bold text-center mt-md-5 subHead' style={{ letterSpacing: '1px', color: '#3473d8ff' }}>Obstetrics & Gynecology</h2>
         <p className='text-secondary opacity-75 contents' style={{textAlign:'justify'}}>The Obstetrics & Gynecology Department supports women’s health needs from adolescence through motherhood and beyond. With specialists like Dr. Lakshmi Varma (MBBS, MD) and Dr. Reena Thomas (MBBS, DGO), the department handles high-risk pregnancies, fertility assessments, menstrual disorders, and laparoscopic surgeries. Procedures include C-sections, normal deliveries, laparoscopic cyst removal, fibroid surgery, hysteroscopy, and infertility-related interventions. The department provides antenatal counseling, breastfeeding assistance, menopausal care, and well-woman screening packages. Modern facilities include a state-of-the-art labor suite, fetal ultrasound unit, neonatal support team, and dedicated maternity recovery rooms.</p>

         <h2 className='fw-bold text-center mt-md-5 subHead' style={{ letterSpacing: '1px', color: '#3473d8ff' }}>Neurology</h2>
         <p className='text-secondary opacity-75 contents' style={{textAlign:'justify'}}>The Neurology Department treats disorders of the brain, spine, and nervous system with a highly trained team led by Dr. Adarsh Nair (MBBS, MD, DM Neurology) and Dr. Meera Shaji (Neurophysician, MBBS, DNB). The department manages stroke, epilepsy, migraines, neuropathies, movement disorders, and memory-related conditions. Procedures include EEG, EMG, nerve conduction studies, stroke thrombolysis, and neurological rehabilitation. Services cover seizure clinics, headache management, cognitive therapy, and neuro-critical care. Facilities include a dedicated Neuro ICU, advanced imaging support, a fully equipped EEG/EMG lab, and a specialized unit for continuous neurological monitoring.</p>

         <h2 className='fw-bold text-center mt-md-5 subHead' style={{ letterSpacing: '1px', color: '#3473d8ff' }}>General Medicine</h2>
         <p className='text-secondary opacity-75 contents' style={{textAlign:'justify'}}>The General Medicine Department provides comprehensive primary and preventive healthcare for adults. Specialists like Dr. Ashok Kumar (MBBS, MD) and Dr. Riya Samuel (MBBS, MD) diagnose and manage chronic illnesses including diabetes, thyroid disorders, hypertension, infectious diseases, and metabolic conditions. Procedures include annual health check-ups, diabetes management plans, thyroid profiling, and chronic disease monitoring. The department offers 24×7 physician support, lifestyle counseling, geriatric care, and long-term treatment planning. Facilities include a well-equipped observation ward, in-house laboratory, diagnostic suite, and pharmacy services for seamless treatment.</p>

         <h2 className='fw-bold text-center mt-md-5 subHead' style={{ letterSpacing: '1px', color: '#3473d8ff' }}>Emergency & Trauma Care</h2>
         <p className='text-secondary opacity-75 contents' style={{textAlign:'justify'}}>The Emergency and Trauma Care Department provides rapid, life-saving interventions around the clock. Managed by Dr. Jithin Varghese (MBBS, MEM) and Dr. Karthika Dev (MBBS, MD), the team handles accidents, burns, cardiac arrests, poisonings, respiratory distress, and critical injuries. Procedures include advanced life support, wound closures, fracture stabilization, rapid triage, and emergency medication administration. Services include a 24×7 ambulance fleet, trauma team activation, and emergency resuscitation protocols. Facilities include a high-dependency resuscitation bay, minor OT, dedicated emergency imaging access, and short-stay observation beds for critical monitoring.</p>

         <h2 className='fw-bold text-center mt-md-5 subHead' style={{ letterSpacing: '1px', color: '#3473d8ff' }}>Gastroenterology</h2>
         <p className='text-secondary opacity-75 contents' style={{textAlign:'justify'}}>The Gastroenterology Department manages digestive and liver-related diseases with advanced diagnostic and therapeutic care. Led by Dr. Vivek Suresh (MBBS, MD, DM Gastroenterology) and Dr. Malavika Dinesh (MBBS, DNB), the team handles gastritis, liver disorders, pancreatitis, ulcers, and intestinal conditions. Procedures include endoscopy, colonoscopy, ERCP, liver biopsy, and polyp removal. Services include diet counseling, liver care clinics, IBS management, and screening for colon and stomach cancers. The department is equipped with a modern endoscopy suite, recovery bay, ultrasound support, and sterile procedure rooms.</p>

         <h2 className='fw-bold text-center mt-md-5 subHead' style={{ letterSpacing: '1px', color: '#3473d8ff' }}>Nephrology</h2>
         <p className='text-secondary opacity-75 contents' style={{textAlign:'justify'}}>The Nephrology Department provides care for kidney-related disorders and dialysis support. Specialists Dr. Hari Venu (MBBS, MD, DM Nephrology) and Dr. Priya Johny (MBBS, DNB Nephrology) manage acute kidney injury, chronic kidney disease, electrolyte disorders, and transplant evaluation. Procedures include hemodialysis, peritoneal dialysis, kidney biopsy, and vascular access care. Services include renal diet programs, fluid management clinics, and transplant readiness assessments. Facilities feature a hygienic dialysis center, isolation units, continuous monitoring systems, and emergency renal care support.</p>
    </div>
    </>
  )
}

export default Departments